version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "6432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data_1:/var/lib/postgresql/data

  postgraphile:
    depends_on:
      - postgres
    build: .
    ports:
      - "5678:5678"
    volumes:
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.yarn/:/app/.yarn/
      - ./.yarnrc.yml:/app/.yarnrc.yml
      - ./graphile.config.ts:/app/graphile.config.ts
      - ./plugin.ts:/app/plugin.ts
      - ./tags.json5:/app/tags.json5
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/appdb
      - GRAPHILE_ENV=development
      - DEBUG=@dataplan/pg:PgExecutor:verbose
    entrypoint: >
      sh -c "
        yarn --frozen-lockfile
        until pg_isready -h postgres -p 5432 -U postgres; do
          echo 'Waiting for Postgres...';
          sleep 1;
        done;
        exec yarn postgraphile -n 0.0.0.0
      "

volumes:
  postgres_data_1: