drop schema if exists app_public cascade;
create schema app_public;

drop role if exists authenticated;
create role authenticated;

grant usage on schema app_public to authenticated;

CREATE TABLE app_public.comments (
    id integer primary key generated by default as identity,
    box box not null,
    boxes box[] not null
);

grant select on table app_public.comments to authenticated;

insert into app_public.comments (box, boxes) values
    ('((0,0),(2,2))'::box, ARRAY['((1,1),(2,2))'::box, '((3,3),(4,4))'::box]),
    ('((10,10),(20,20))'::box, ARRAY['((5,5),(6,6))'::box, '((7,7),(8,8))'::box]);
